#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --time=1440 #or –t, max wall time, in min
#SBATCH --cpus-per-task=19 #or –c, max CPUs for the job
#SBATCH --partition=medium #or –p, partition to run job on
module load R
module load bgenix
chr=$1
if [ $chr -eq 0 ]
then 
	Rscript '/home/zmx21/MRC_BSU_Internship/Target_Gene_Interactions/GxG_Interactions.R'
else
	path="~/bsu_scratch/UKB_Data/"
        sample_file_prefix="ukbb_metadata_with_PC"
        bgen_file_prefix="ukb_imp_chr#_HRConly"
        chr=$SLURM_ARRAY_TASK_ID
        phenotype="sbp"
        targetRS=$1
        out_suffix=$2
        eur_only=1
        cov='sex,ages,bmi'
        PC=5
        med=1
        MAF='0.01'
        info='0.5'
        n_cores=12
        chunks='1,end'
        training_set='~/bsu_scratch/UKB_Data/training_set.rds'
        Rscript '/home/zmx21/MRC_BSU_Internship/Target_Gene_Interactions/GxG_Interactions.R' $path $sample_file_prefix $bgen_file_prefix $chr $phenotype $targetRS $out_suffix $eur_only $cov $PC $med $MAF $info
 $n_cores $chunks $training_set
fi
