#!/bin/bash
chr=$1
if [ $chr -eq 0 ]
then 
	Rscript '/home/zmx21/MRC_BSU_Internship/Target_Gene_Interactions/GxG_Interactions.R'
else
	path="/mrc-bsu/scratch/zmx21/UKB_Data/"
        sample_file_prefix="ukbb_metadata"
        bgen_file_prefix="ukb_imp_chr#_HRConly"
        phenotype="sbp"
        targetRS=$2
        out_suffix=$3
        cov=$4
        eur_only=1
	MAF=0.01
        info=0.5
        n_cores=16
        Rscript '/home/zmx21/MRC_BSU_Internship/Target_Gene_Interactions/GxG_Interactions.R' $path $sample_file_prefix $bgen_file_prefix $chr $phenotype $targetRS $out_suffix $eur_only $cov $MAF $info $n_cores
fi
